plugin:
    name: 'ibsellnet.downloadmediafiles::lang.plugin.name'
    description: 'ibsellnet.downloadmediafiles::lang.plugin.description'
    author: ibsellnet
    icon: oc-icon-slideshare
    homepage: ''